[versions]
agp = "9.0.1"
arsceneview = "0.10.0"
arsceneviewVersion = "0.10.0"
activityCompose = "1.13.0"
composeBom = "2024.09.00"
kotlin = "2.2.10"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
lifecycleRuntimeKtx = "2.9.0"
material = "1.12.0"
constraintlayout = "2.2.1"
navigationFragmentKtx = "2.9.0"
navigationUiKtx = "2.9.0"
core = "1.17.1"
okhttp = "4.9.3"
sceneform = "1.21.0"
sceneview = "1.1.0"
glide = "4.16.0"
firebaseDatabaseKtx = "21.0.0"
sceneformBase = "1.17.1"

[libraries]
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
arsceneview = { module = "io.github.sceneview:arsceneview", version.ref = "arsceneviewVersion" }
github-sceneview = { module = "io.github.sceneview:sceneview", version.ref = "sceneview" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
sceneview = { group = "io.github.sceneview", name = "sceneform", version = "1.22.0" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
core = { group = "com.google.ar.sceneform", name = "core", version.ref = "core" }
sceneform = { module = "com.gorisse.thomas.sceneform:sceneform", version.ref = "sceneform" }
firebase-database-ktx = { group = "com.google.firebase", name = "firebase-database-ktx", version.ref = "firebaseDatabaseKtx" }
sceneform-base = { group = "com.google.ar.sceneform", name = "sceneform-base", version.ref = "sceneformBase" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

